### ISSUE TITLE
Error loading the plug-in

### ISSUE THREAD

**Issue by Nicode70** [wibberryd/homebridge-rpi-rts#14]
Hi! I've followed all the steps for the setup, but i get this error message when homebridge restarts:
[5/1/2021, 15:01:12] ====================
[5/1/2021, 15:01:12] ERROR LOADING PLUGIN homebridge-rpi-rts:
[5/1/2021, 15:01:12] Error: pigpio error -1 in gpioInitialise
    at initializePigpio (/usr/local/lib/node_modules/homebridge-rpi-rts/node_modules/pigpio/pigpio.js:54:12)
    at new Gpio (/usr/local/lib/node_modules/homebridge-rpi-rts/node_modules/pigpio/pigpio.js:158:5)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-rpi-rts/RpiGpioRts.js:6:16)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-rpi-rts/index.js:1:20)
[5/1/2021, 15:01:12] ====================

Could you please help me?

**Comment by Nicode70** [comment]
sorry, red the first issue and solved the problem.
