### ISSUE TITLE
Error 'initMboxBlock: init mbox zaps failed' at Homebridge startup

### ISSUE THREAD

**Issue by AragornSRB** [wibberryd/homebridge-rpi-rts#5]
Everything works fine for 1 day and then error started to show :(.Then i do backup of homebridge and set up everything again and then works(for 1 day :))

initMboxBlock: init mbox zaps failed

ERROR LOADING PLUGIN homebridge-rpi-rts:
[20/01/2021, 17:36:46] Error: pigpio error -1 in gpioInitialise
    at initializePigpio (/usr/lib/node_modules/homebridge-rpi-rts/node_modules/pigpio/pigpio.js:54:12)
    at new Gpio (/usr/lib/node_modules/homebridge-rpi-rts/node_modules/pigpio/pigpio.js:158:5)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-rpi-rts/RpiGpioRts.js:6:16)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-rpi-rts/index.js:1:20)

Error loading accessory requested in your config.json at position 1
[20/01/2021, 17:36:47] Error: The requested accessory 'Somfy RTS Remote' was not registered by any plugin.
    at PluginManager.getPluginForAccessory (/usr/lib/node_modules/homebridge/src/pluginManager.ts:198:15)
    at /usr/lib/node_modules/homebridge/src/server.ts:347:37
    at Array.forEach (<anonymous>)
    at Server._loadAccessories (/usr/lib/node_modules/homebridge/src/server.ts:330:29)
    at Server.start (/usr/lib/node_modules/homebridge/src/server.ts:156:12)
    at cli (/usr/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)

**Comment by Ryamonster10** [comment]
Me too, I have the same problem, looking though what he changed, the second error should not have happened, although maybe adding .toString() at the end of the saving rolling code script made the first error.

**Comment by Ryamonster10** [comment]
I am going to try the version before this and see if that works.

**Comment by wibberryd** [comment]
Yes, I got this error too and I'm not sure why it happened. The error was occurring when the pigpio library was initializing. I tried to restart hb-service: no success, reinstall the plugin: no success, reinstall the pigpio C library: no success, switch back to version 1.0.1 of the plugin: no success. But it disappeared by itself when I restarted the Raspberry Pi.

**Comment by Ryamonster10** [comment]
So is this in V 1.0.1 that it go's away by itself or V 1.0.2?

**Comment by AragornSRB** [comment]
Can this be memory problem? 
initMboxBlock: init mbox zaps failed
https://raspberrypi.stackexchange.com/questions/29983/pigpio-initialization-failing-with-init-mbox-zaps-failed

**Comment by Ryamonster10** [comment]
It may be, but why the did it not happen in V1.0.1?

**Comment by AragornSRB** [comment]
i dont know, V1.0.1 never worked for me :(

**Comment by Ryamonster10** [comment]
Huh, that was the only version that worked for me...

**Comment by wibberryd** [comment]
> Can this be memory problem?
> initMboxBlock: init mbox zaps failed

@AragornSRB Thank you for pointing this out. It looks like a possible cause of this error. Also, I only get this error after restarting many times Homebridge (I would say after 15-30 restarts). If the memory is not cleaned up upon exit, it seems normal that memory problems arise after some time.

I am trying to find a way to catch the exit/restart events to perform the memory cleanup. I tried to catch the Node.js process events: `process.on('exit', () => { pigpio.terminate(); });`, without success. I also tried with the other 'catchable' events: `'SIGINT', 'SIGTERM', 'SIGUSR1', 'SIGUSR2', 'uncaughtException'`, also without success. So I need to investigate a bit further...


> It may be, but why the did it not happen in V1.0.1?

@Ryamonster10 I don't know. Maybe the problem was already there, but since I almost never restarted Homebridge, I did not come upon this error?


> i dont know, V1.0.1 never worked for me :(

@AragornSRB v1.0.1 stopped working on my Pi when I upgraded Node.js from version 12 to version 14. So it may be incompatible with Node.js 14.

**Comment by Ryamonster10** [comment]
Now my problem is that no matter how meny times I reboot the pi it just gives the same error,
```
[01/02/2021, 11:47:32] ====================
[01/02/2021, 11:47:32] ERROR LOADING PLUGIN homebridge-rpi-rts:
[01/02/2021, 11:47:32] Error: pigpio error -1 in gpioInitialise
    at initializePigpio (/usr/local/lib/node_modules/homebridge-rpi-rts/node_modules/pigpio/pigpio.js:54:12)
    at new Gpio (/usr/local/lib/node_modules/homebridge-rpi-rts/node_modules/pigpio/pigpio.js:158:5)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-rpi-rts/RpiGpioRts.js:6:16)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-rpi-rts/index.js:1:20)
[01/02/2021, 11:47:32] ====================
[01/02/2021, 11:47:32] Loading 1 platforms...
[01/02/2021, 11:47:32] [Config] Initializing config platform...
[01/02/2021, 11:47:32] [Config] Spawning homebridge-config-ui-x with PID 1070
[01/02/2021, 11:47:32] Loading 1 accessories...
[01/02/2021, 11:47:32] Error loading accessory requested in your config.json at position 1
[01/02/2021, 11:47:32] Error: The requested accessory 'Somfy RTS Remote' was not registered by any plugin.
    at PluginManager.getPluginForAccessory (/usr/local/lib/node_modules/homebridge/src/pluginManager.ts:198:15)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:347:37
    at Array.forEach (<anonymous>)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/src/server.ts:330:29)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:156:12)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
``` 
Only just seeing this now as my problem before was getting hb-service to work.

**Comment by wibberryd** [comment]
@Ryamonster10, Is there another error mentioned before that in the log?

On the Homebridge Raspbian image I ran into the error `Can't lock /var/run/pigpio.pid` which was solved with the command `sudo killall pigpiod`. The problem was that a pigpio daemon had already locked the access to /var/run/pigpio.pid preventing the Homebridge plugin from locking the same resource.

**Comment by Ryamonster10** [comment]
Nope, this is my full log:
```
[01/02/2021, 12:11:07] [HB Supervisor] Started Homebridge v1.1.7 with PID: 1878
[01/02/2021, 12:11:10] Loaded config.json with 1 accessories and 1 platforms.
[01/02/2021, 12:11:10] ---
[01/02/2021, 12:11:13] Loaded plugin: homebridge-config-ui-x@4.37.0
[01/02/2021, 12:11:13] Registering platform 'homebridge-config-ui-x.config'
[01/02/2021, 12:11:13] ---
2021-02-01 12:11:13 initInitialise: Can't lock /var/run/pigpio.pid
[01/02/2021, 12:11:13] ====================
[01/02/2021, 12:11:13] ERROR LOADING PLUGIN homebridge-rpi-rts:
[01/02/2021, 12:11:13] Error: pigpio error -1 in gpioInitialise
    at initializePigpio (/usr/local/lib/node_modules/homebridge-rpi-rts/node_modules/pigpio/pigpio.js:54:12)
    at new Gpio (/usr/local/lib/node_modules/homebridge-rpi-rts/node_modules/pigpio/pigpio.js:158:5)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-rpi-rts/RpiGpioRts.js:6:16)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-rpi-rts/index.js:1:20)
[01/02/2021, 12:11:13] ====================
[01/02/2021, 12:11:13] Loading 1 platforms...
[01/02/2021, 12:11:13] [Config] Initializing config platform...
[01/02/2021, 12:11:13] [Config] Running in Service Mode
[01/02/2021, 12:11:13] Loading 1 accessories...
[01/02/2021, 12:11:13] Error loading accessory requested in your config.json at position 1
[01/02/2021, 12:11:13] Error: The requested accessory 'Somfy RTS Remote' was not registered by any plugin.
    at PluginManager.getPluginForAccessory (/usr/local/lib/node_modules/homebridge/src/pluginManager.ts:198:15)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:347:37
    at Array.forEach (<anonymous>)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/src/server.ts:330:29)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:156:12)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
[01/02/2021, 12:11:13] Got SIGTERM, shutting down Homebridge...
```

**Comment by Ryamonster10** [comment]
Yes, thanks so much, that worked, now all the errors are gone! Thanks so much again.

**Comment by Ryamonster10** [comment]
Ok, so although that works, every time something happens that you need to reboot or restart, you have to run the command over and over again.

**Comment by nicolasherrbach** [comment]
Ah yes, indeed. The command `sudo systemctl disable pigpiod` should disable this service permanently.

**Comment by wibberryd** [comment]
Ah yes, indeed. The command `sudo systemctl disable pigpiod` should disable this service permanently.

**Comment by Ryamonster10** [comment]
Thank you!

**Comment by s54b32julian** [comment]
edit: something is wrong with code embedding, sorry for that! 

I can't get the plugin to work, looks like the issue from @Ryamonster10 . 
I´m on latest node, homebridge etc. And made all modifications to homebridge. Also tried "sudo systemctl disable pigpiod" and "sudo killall pigpiod"

If i run " sudo homebridge" i get:


[08/05/2021, 17:24:20] ====================
[08/05/2021, 17:24:20] ERROR LOADING PLUGIN homebridge-rpi-rts:
[08/05/2021, 17:24:20] Error: pigpio error -1 in gpioInitialise
    at initializePigpio (/usr/local/lib/node_modules/homebridge-rpi-rts/node_modules/pigpio/pigpio.js:54:12)
    at new Gpio (/usr/local/lib/node_modules/homebridge-rpi-rts/node_modules/pigpio/pigpio.js:158:5)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-rpi-rts/RpiGpioRts.js:6:16)
    at Module._compile (internal/modules/cjs/loader.js:1118:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1138:10)
    at Module.load (internal/modules/cjs/loader.js:982:32)
    at Function.Module._load (internal/modules/cjs/loader.js:875:14)
    at Module.require (internal/modules/cjs/loader.js:1022:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-rpi-rts/index.js:1:20)




and if i run "homebridge" i get:

[08/05/2021, 17:27:40] Loaded plugin: homebridge-config-ui-x@4.41.1
[08/05/2021, 17:27:40] Registering platform 'homebridge-config-ui-x.config'
[08/05/2021, 17:27:40] ---
2021-05-08 17:27:40 initCheckPermitted: 
+---------------------------------------------------------+
|Sorry, you don't have permission to run this program.    |
|Try running as root, e.g. precede the command with sudo. |
+---------------------------------------------------------+


[08/05/2021, 17:27:40] ====================
[08/05/2021, 17:27:40] ERROR LOADING PLUGIN homebridge-rpi-rts:
[08/05/2021, 17:27:40] Error: pigpio error -1 in gpioInitialise
    at initializePigpio (/usr/local/lib/node_modules/homebridge-rpi-rts/node_modules/pigpio/pigpio.js:54:12)
    at new Gpio (/usr/local/lib/node_modules/homebridge-rpi-rts/node_modules/pigpio/pigpio.js:158:5)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-rpi-rts/RpiGpioRts.js:6:16)
    at Module._compile (internal/modules/cjs/loader.js:1118:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1138:10)
    at Module.load (internal/modules/cjs/loader.js:982:32)
    at Function.Module._load (internal/modules/cjs/loader.js:875:14)
    at Module.require (internal/modules/cjs/loader.js:1022:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-rpi-rts/index.js:1:20)
